import { 
  User, Cooperative, Member, Transaction, Product, Order, Announcement, Application, Report,
  ActivityLog, MemberRequest, ApprovalRequest, ProductReview, FavoriteProduct,
  CooperativeDocument, MemberFinancialRecord
} from '../types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@cooperativehub.rw',
    role: 'super_admin',
    phone: '+250788123456',
  },
  {
    id: '2',
    name: 'Jean Baptiste Mugabo',
    email: 'jb.mugabo@terimbere.coop',
    role: 'cooperative_admin',
    cooperativeId: 'coop1',
    cooperativeRole: 'admin',
    phone: '+250788234567',
  },
  {
    id: '3',
    name: 'Marie Claire Uwase',
    email: 'marie@terimbere.coop',
    role: 'member',
    cooperativeId: 'coop1',
    cooperativeRole: 'member',
    phone: '+250788345678',
  },
  {
    id: '4',
    name: 'David Nkurunziza',
    email: 'david@buyer.com',
    role: 'buyer',
    phone: '+250788456789',
  },
  {
    id: '5',
    name: 'RCA Officer',
    email: 'officer@rca.gov.rw',
    role: 'regulator',
    phone: '+250788567890',
  },
  {
    id: '6',
    name: 'Alice Mukamana',
    email: 'alice@terimbere.coop',
    role: 'member',
    cooperativeId: 'coop1',
    cooperativeRole: 'accountant',
    phone: '+250788345679',
  },
  {
    id: '7',
    name: 'Patrick Habimana',
    email: 'patrick@terimbere.coop',
    role: 'member',
    cooperativeId: 'coop1',
    cooperativeRole: 'secretary',
    phone: '+250788456790',
  },
];

// Mock Cooperatives
export const mockCooperatives: Cooperative[] = [
  {
    id: 'coop1',
    name: 'Terimbere Coffee Cooperative',
    type: 'Agriculture - Coffee',
    registrationNumber: 'RCA/2020/0145',
    location: 'Huye District, Southern Province',
    province: 'Southern Province',
    district: 'Huye',
    sector: 'Tumba',
    description: 'A cooperative of coffee farmers dedicated to producing high-quality specialty coffee for export and local markets.',
    establishedDate: '2020-03-15',
    memberCount: 156,
    chairperson: 'Jean Baptiste Mugabo',
    treasurer: 'Alice Mukamana',
    secretary: 'Patrick Habimana',
    bankAccount: 'BK-1234567890',
    mobileMoneyAccount: '078-812-3456',
    status: 'active',
  },
  {
    id: 'coop2',
    name: 'Imbuto Dairy Cooperative',
    type: 'Agriculture - Dairy',
    registrationNumber: 'RCA/2019/0089',
    location: 'Nyagatare District, Eastern Province',
    province: 'Eastern Province',
    district: 'Nyagatare',
    sector: 'Karama',
    description: 'Dairy farmers collective focusing on milk production and processing.',
    establishedDate: '2019-06-20',
    memberCount: 89,
    chairperson: 'Emmanuel Nshimiyimana',
    treasurer: 'Grace Uwera',
    secretary: 'Joseph Niyonzima',
    status: 'active',
  },
  {
    id: 'coop3',
    name: 'Ubumwe Handicraft Cooperative',
    type: 'Handicrafts',
    registrationNumber: 'RCA/2021/0234',
    location: 'Kigali City',
    province: 'Kigali City',
    district: 'Gasabo',
    sector: 'Remera',
    description: 'Artisan cooperative producing traditional Rwandan handicrafts and modern designs.',
    establishedDate: '2021-01-10',
    memberCount: 45,
    chairperson: 'Vestine Mukaneza',
    treasurer: 'Eric Habineza',
    secretary: 'Claudine Uwamahoro',
    status: 'active',
  },
  {
    id: 'coop4',
    name: 'Abakundakawa Tea Growers Cooperative',
    type: 'Agriculture - Tea',
    registrationNumber: 'PENDING',
    location: 'Rulindo District, Northern Province',
    province: 'Northern Province',
    district: 'Rulindo',
    sector: 'Base',
    description: 'New cooperative of tea farmers seeking to improve production and market access.',
    establishedDate: '2025-10-01',
    memberCount: 78,
    chairperson: 'Samuel Nkuranga',
    treasurer: 'Josephine Mukandori',
    secretary: 'Robert Habimana',
    status: 'pending',
    registeredDate: '2025-10-05',
    adminEmail: 'samuel@abakundakawa.coop',
    adminPhone: '+250788567890',
  },
  {
    id: 'coop5',
    name: 'Dukundane Savings & Credit Cooperative',
    type: 'Savings & Credit',
    registrationNumber: 'PENDING',
    location: 'Muhanga District, Southern Province',
    province: 'Southern Province',
    district: 'Muhanga',
    sector: 'Cyeza',
    description: 'Community-based savings and credit cooperative to support small businesses.',
    establishedDate: '2025-09-28',
    memberCount: 125,
    chairperson: 'Christine Uwimana',
    treasurer: 'Patrick Nsengimana',
    secretary: 'Alice Mukasine',
    status: 'pending',
    registeredDate: '2025-10-08',
    adminEmail: 'christine@dukundane.coop',
    adminPhone: '+250788678901',
  },
  {
    id: 'coop6',
    name: 'Iwacu Honey Production Cooperative',
    type: 'Agriculture - Other',
    registrationNumber: 'PENDING',
    location: 'Nyamagabe District, Southern Province',
    province: 'Southern Province',
    district: 'Nyamagabe',
    sector: 'Gasaka',
    description: 'Beekeepers cooperative focused on organic honey production and processing.',
    establishedDate: '2025-10-10',
    memberCount: 34,
    chairperson: 'Eric Habimana',
    treasurer: 'Beatrice Uwera',
    secretary: 'Jean Bosco Nshimiyimana',
    status: 'pending',
    registeredDate: '2025-10-12',
    adminEmail: 'eric@iwacuhoney.coop',
    adminPhone: '+250788789012',
  },
];

// Mock Members
export const mockMembers: Member[] = [
  {
    id: 'm1',
    cooperativeId: 'coop1',
    name: 'Jean Baptiste Mugabo',
    email: 'jb.mugabo@terimbere.coop',
    phone: '+250788234567',
    role: 'admin',
    joinDate: '2020-03-15',
    contributions: 850000,
    shares: 17,
    status: 'active',
  },
  {
    id: 'm2',
    cooperativeId: 'coop1',
    name: 'Alice Mukamana',
    email: 'alice@terimbere.coop',
    phone: '+250788345678',
    role: 'accountant',
    joinDate: '2020-03-15',
    contributions: 750000,
    shares: 15,
    status: 'active',
  },
  {
    id: 'm3',
    cooperativeId: 'coop1',
    name: 'Patrick Habimana',
    email: 'patrick@terimbere.coop',
    phone: '+250788456789',
    role: 'secretary',
    joinDate: '2020-03-20',
    contributions: 600000,
    shares: 12,
    status: 'active',
  },
  {
    id: 'm4',
    cooperativeId: 'coop1',
    name: 'Marie Claire Uwase',
    email: 'marie@terimbere.coop',
    phone: '+250788567890',
    role: 'member',
    joinDate: '2020-05-10',
    contributions: 500000,
    shares: 10,
    status: 'active',
  },
  {
    id: 'm5',
    cooperativeId: 'coop1',
    name: 'Claude Nkurunziza',
    email: 'claude@terimbere.coop',
    phone: '+250788678901',
    role: 'member',
    joinDate: '2020-08-15',
    contributions: 450000,
    shares: 9,
    status: 'active',
  },
];

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: 't1',
    cooperativeId: 'coop1',
    type: 'income',
    category: 'Product Sales',
    amount: 2500000,
    description: 'Coffee beans sale to export company',
    date: '2025-10-05',
    recordedBy: 'Alice Mukamana',
    paymentMethod: 'Bank Transfer',
    blockchainHash: '0x7f3e9a2b...',
  },
  {
    id: 't2',
    cooperativeId: 'coop1',
    type: 'expense',
    category: 'Operational Costs',
    amount: 350000,
    description: 'Fertilizer and farming supplies',
    date: '2025-10-03',
    recordedBy: 'Alice Mukamana',
    paymentMethod: 'Mobile Money',
  },
  {
    id: 't3',
    cooperativeId: 'coop1',
    type: 'contribution',
    category: 'Member Contributions',
    amount: 500000,
    description: 'Monthly member contributions',
    date: '2025-10-01',
    recordedBy: 'Alice Mukamana',
    paymentMethod: 'Mobile Money',
    blockchainHash: '0x4d2a1c8f...',
  },
  {
    id: 't4',
    cooperativeId: 'coop1',
    type: 'income',
    category: 'Product Sales',
    amount: 1800000,
    description: 'Local market sales',
    date: '2025-09-28',
    recordedBy: 'Alice Mukamana',
    paymentMethod: 'Cash',
  },
  {
    id: 't5',
    cooperativeId: 'coop1',
    type: 'expense',
    category: 'Salaries',
    amount: 450000,
    description: 'Worker salaries',
    date: '2025-09-30',
    recordedBy: 'Alice Mukamana',
    paymentMethod: 'Mobile Money',
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: 'p1',
    cooperativeId: 'coop1',
    cooperativeName: 'Terimbere Coffee Cooperative',
    name: 'Premium Arabica Coffee Beans',
    description: 'Fully washed, sun-dried specialty coffee beans from the highlands of Huye. Notes of caramel, chocolate, and citrus.',
    category: 'Coffee',
    price: 12000,
    unit: 'kg',
    availableStock: 500,
    minOrder: 5,
    images: ['coffee-beans'],
    location: 'Huye, Southern Province',
    status: 'available',
    createdAt: '2025-09-01',
  },
  {
    id: 'p2',
    cooperativeId: 'coop1',
    cooperativeName: 'Terimbere Coffee Cooperative',
    name: 'Roasted Ground Coffee',
    description: 'Medium roast ground coffee, perfect for pour-over and French press brewing.',
    category: 'Coffee',
    price: 15000,
    unit: 'kg',
    availableStock: 200,
    minOrder: 2,
    images: ['coffee-ground'],
    location: 'Huye, Southern Province',
    status: 'available',
    createdAt: '2025-09-15',
  },
  {
    id: 'p3',
    cooperativeId: 'coop2',
    cooperativeName: 'Imbuto Dairy Cooperative',
    name: 'Fresh Cow Milk',
    description: 'Fresh, pasteurized cow milk from grass-fed cows. Delivered daily.',
    category: 'Dairy',
    price: 800,
    unit: 'liter',
    availableStock: 1000,
    minOrder: 10,
    images: ['milk'],
    location: 'Nyagatare, Eastern Province',
    status: 'available',
    createdAt: '2025-09-20',
  },
  {
    id: 'p4',
    cooperativeId: 'coop3',
    cooperativeName: 'Ubumwe Handicraft Cooperative',
    name: 'Agaseke Traditional Basket',
    description: 'Handwoven traditional Rwandan peace basket with lid. Made from natural sisal and sweetgrass.',
    category: 'Handicrafts',
    price: 25000,
    unit: 'piece',
    availableStock: 50,
    minOrder: 1,
    images: ['basket'],
    location: 'Kigali City',
    status: 'available',
    createdAt: '2025-08-10',
  },
];

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: 'o1',
    productId: 'p1',
    productName: 'Premium Arabica Coffee Beans',
    cooperativeId: 'coop1',
    cooperativeName: 'Terimbere Coffee Cooperative',
    buyerId: '4',
    buyerName: 'David Nkurunziza',
    buyerPhone: '+250788456789',
    quantity: 50,
    totalPrice: 600000,
    status: 'confirmed',
    paymentMethod: 'Bank Transfer',
    paymentStatus: 'paid',
    orderDate: '2025-10-10',
    deliveryDate: '2025-10-15',
  },
  {
    id: 'o2',
    productId: 'p4',
    productName: 'Agaseke Traditional Basket',
    cooperativeId: 'coop3',
    cooperativeName: 'Ubumwe Handicraft Cooperative',
    buyerId: '4',
    buyerName: 'David Nkurunziza',
    buyerPhone: '+250788456789',
    quantity: 10,
    totalPrice: 250000,
    status: 'pending',
    paymentMethod: 'Mobile Money',
    paymentStatus: 'pending',
    orderDate: '2025-10-12',
  },
];

// Mock Announcements
export const mockAnnouncements: Announcement[] = [
  {
    id: 'a1',
    cooperativeId: 'coop1',
    cooperativeName: 'Terimbere Coffee Cooperative',
    type: 'job',
    title: 'Coffee Processing Supervisor',
    description: 'We are looking for an experienced supervisor to oversee our coffee processing operations. Responsibilities include quality control, team management, and ensuring adherence to processing standards.',
    location: 'Huye District',
    deadline: '2025-10-30',
    requirements: [
      'Minimum 3 years experience in coffee processing',
      'Leadership and management skills',
      'Knowledge of specialty coffee standards',
      'Fluent in Kinyarwanda and English',
    ],
    contactPerson: 'Jean Baptiste Mugabo',
    contactPhone: '+250788234567',
    visibility: 'public',
    status: 'active',
    postedDate: '2025-10-01',
    applicants: 12,
  },
  {
    id: 'a2',
    cooperativeId: 'coop2',
    cooperativeName: 'Imbuto Dairy Cooperative',
    type: 'training',
    title: 'Modern Dairy Farming Techniques Workshop',
    description: 'Free training workshop on modern dairy farming practices, including feed management, disease prevention, and milk quality improvement.',
    location: 'Nyagatare District',
    deadline: '2025-10-20',
    contactPerson: 'Emmanuel Nshimiyimana',
    contactPhone: '+250788345678',
    visibility: 'public',
    status: 'active',
    postedDate: '2025-10-05',
    applicants: 34,
  },
  {
    id: 'a3',
    cooperativeId: 'coop1',
    cooperativeName: 'Terimbere Coffee Cooperative',
    type: 'meeting',
    title: 'Monthly General Assembly',
    description: 'Monthly cooperative meeting to discuss harvest progress, financial reports, and upcoming projects.',
    location: 'Cooperative Headquarters, Tumba',
    deadline: '2025-10-18',
    contactPerson: 'Patrick Habimana',
    contactPhone: '+250788456789',
    visibility: 'members_only',
    status: 'active',
    postedDate: '2025-10-08',
  },
  {
    id: 'a4',
    cooperativeId: 'coop3',
    cooperativeName: 'Ubumwe Handicraft Cooperative',
    type: 'tender',
    title: 'Bulk Order: 500 Traditional Baskets',
    description: 'Seeking partnership with artisans for a bulk order of traditional Rwandan baskets for an international client.',
    location: 'Kigali City',
    deadline: '2025-10-25',
    requirements: [
      'Ability to produce high-quality baskets',
      'Meet production deadline',
      'Competitive pricing',
    ],
    contactPerson: 'Vestine Mukaneza',
    contactPhone: '+250788567890',
    visibility: 'public',
    status: 'active',
    postedDate: '2025-10-07',
    applicants: 8,
  },
];

// Mock Reports
export const mockReports: Report[] = [
  {
    id: 'r1',
    cooperativeId: 'coop1',
    type: 'monthly',
    period: 'September 2025',
    totalIncome: 5800000,
    totalExpenses: 1250000,
    netProfit: 4550000,
    memberContributions: 500000,
    generatedDate: '2025-10-01',
    generatedBy: 'Alice Mukamana',
  },
  {
    id: 'r2',
    cooperativeId: 'coop1',
    type: 'quarterly',
    period: 'Q3 2025',
    totalIncome: 18500000,
    totalExpenses: 4200000,
    netProfit: 14300000,
    memberContributions: 1500000,
    generatedDate: '2025-10-01',
    generatedBy: 'Alice Mukamana',
  },
];

// Mock Activity Logs
export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log1',
    userId: '2',
    userName: 'Jean Baptiste Mugabo',
    userRole: 'cooperative_admin',
    cooperativeId: 'coop1',
    action: 'member_invited',
    description: 'Invited new member Marie Claire Uwase',
    timestamp: '2025-10-20T10:30:00Z',
    ipAddress: '197.243.10.45',
  },
  {
    id: 'log2',
    userId: '6',
    userName: 'Alice Mukamana',
    userRole: 'accountant',
    cooperativeId: 'coop1',
    action: 'transaction_recorded',
    description: 'Recorded income transaction: Coffee beans sale',
    timestamp: '2025-10-20T14:15:00Z',
    metadata: { amount: 2500000, type: 'income' },
  },
  {
    id: 'log3',
    userId: '1',
    userName: 'Admin User',
    userRole: 'super_admin',
    action: 'cooperative_approved',
    description: 'Approved cooperative registration for Terimbere Coffee Cooperative',
    timestamp: '2025-10-19T09:00:00Z',
  },
  {
    id: 'log4',
    userId: '7',
    userName: 'Patrick Habimana',
    userRole: 'secretary',
    cooperativeId: 'coop1',
    action: 'transaction_approved',
    description: 'Approved expense transaction for fertilizer purchase',
    timestamp: '2025-10-18T16:45:00Z',
    metadata: { amount: 350000, type: 'expense' },
  },
];

// Mock Member Requests
export const mockMemberRequests: MemberRequest[] = [
  {
    id: 'req1',
    memberId: 'm4',
    memberName: 'Marie Claire Uwase',
    cooperativeId: 'coop1',
    type: 'loan',
    title: 'Agricultural Equipment Loan',
    description: 'Requesting a loan of 500,000 RWF to purchase new farming equipment',
    amount: 500000,
    status: 'pending',
    submittedDate: '2025-10-20',
  },
  {
    id: 'req2',
    memberId: 'm5',
    memberName: 'Claude Nkurunziza',
    cooperativeId: 'coop1',
    type: 'withdrawal',
    title: 'Savings Withdrawal',
    description: 'Request to withdraw 200,000 RWF from savings for emergency medical expenses',
    amount: 200000,
    status: 'approved',
    submittedDate: '2025-10-15',
    reviewedBy: 'Jean Baptiste Mugabo',
    reviewedDate: '2025-10-16',
    reviewNotes: 'Approved due to medical emergency',
  },
  {
    id: 'req3',
    memberId: 'm3',
    memberName: 'Patrick Habimana',
    cooperativeId: 'coop1',
    type: 'complaint',
    title: 'Delayed Dividend Payment',
    description: 'My dividend payment for Q3 2025 has not been received',
    status: 'pending',
    submittedDate: '2025-10-18',
  },
];

// Mock Approval Requests
export const mockApprovalRequests: ApprovalRequest[] = [
  {
    id: 'apr1',
    cooperativeId: 'coop1',
    type: 'transaction',
    title: 'Large Equipment Purchase',
    description: 'Purchase of coffee processing equipment worth 3,000,000 RWF',
    amount: 3000000,
    initiatedBy: 'Jean Baptiste Mugabo',
    initiatedDate: '2025-10-21',
    requiredApprovals: 2,
    approvals: [
      {
        userId: '6',
        userName: 'Alice Mukamana',
        role: 'accountant',
        approved: true,
        timestamp: '2025-10-21T15:00:00Z',
        notes: 'Budget approved, funds available',
      },
    ],
    status: 'pending',
    metadata: { category: 'equipment', vendor: 'Coffee Tech Ltd' },
  },
  {
    id: 'apr2',
    cooperativeId: 'coop1',
    type: 'loan',
    title: 'Member Loan Approval - Marie Claire',
    description: 'Loan request of 500,000 RWF for agricultural equipment',
    amount: 500000,
    initiatedBy: 'Marie Claire Uwase',
    initiatedDate: '2025-10-20',
    requiredApprovals: 2,
    approvals: [],
    status: 'pending',
  },
];

// Mock Product Reviews
export const mockProductReviews: ProductReview[] = [
  {
    id: 'rev1',
    productId: 'p1',
    cooperativeId: 'coop1',
    buyerId: '4',
    buyerName: 'David Nkurunziza',
    orderId: 'o1',
    rating: 5,
    comment: 'Excellent quality coffee beans! The flavor profile is outstanding.',
    reviewDate: '2025-10-16',
    verified: true,
  },
  {
    id: 'rev2',
    productId: 'p4',
    cooperativeId: 'coop3',
    buyerId: '4',
    buyerName: 'David Nkurunziza',
    orderId: 'o2',
    rating: 4,
    comment: 'Beautiful traditional baskets, well-crafted and authentic.',
    reviewDate: '2025-10-14',
    verified: true,
  },
];

// Mock Favorite Products
export const mockFavoriteProducts: FavoriteProduct[] = [
  {
    id: 'fav1',
    buyerId: '4',
    productId: 'p1',
    cooperativeId: 'coop1',
    addedDate: '2025-10-05',
  },
  {
    id: 'fav2',
    buyerId: '4',
    productId: 'p3',
    cooperativeId: 'coop2',
    addedDate: '2025-10-08',
  },
];

// Mock Cooperative Documents
export const mockCooperativeDocuments: CooperativeDocument[] = [
  {
    id: 'doc1',
    cooperativeId: 'coop1',
    type: 'registration',
    title: 'RCA Registration Certificate',
    description: 'Official registration certificate from Rwanda Cooperative Agency',
    fileUrl: '/documents/rca-cert-coop1.pdf',
    uploadedBy: 'Jean Baptiste Mugabo',
    uploadedDate: '2020-03-15',
    visibility: 'all_members',
  },
  {
    id: 'doc2',
    cooperativeId: 'coop1',
    type: 'constitution',
    title: 'Cooperative Constitution',
    description: 'Governing rules and regulations of the cooperative',
    fileUrl: '/documents/constitution-coop1.pdf',
    uploadedBy: 'Jean Baptiste Mugabo',
    uploadedDate: '2020-03-15',
    visibility: 'all_members',
  },
  {
    id: 'doc3',
    cooperativeId: 'coop1',
    type: 'financial_report',
    title: 'Q3 2025 Financial Report',
    description: 'Quarterly financial performance report',
    fileUrl: '/documents/q3-2025-report-coop1.pdf',
    uploadedBy: 'Alice Mukamana',
    uploadedDate: '2025-10-01',
    visibility: 'all_members',
  },
  {
    id: 'doc4',
    cooperativeId: 'coop1',
    type: 'meeting_minutes',
    title: 'September 2025 General Assembly Minutes',
    description: 'Minutes from the monthly general assembly meeting',
    fileUrl: '/documents/meeting-sept-2025.pdf',
    uploadedBy: 'Patrick Habimana',
    uploadedDate: '2025-09-25',
    visibility: 'all_members',
  },
];

// Mock Member Financial Records
export const mockMemberFinancialRecords: MemberFinancialRecord[] = [
  {
    id: 'fin1',
    memberId: 'm1',
    cooperativeId: 'coop1',
    shares: 17,
    totalContributions: 850000,
    savings: 450000,
    dividends: 120000,
    loans: 0,
    lastUpdated: '2025-10-01',
  },
  {
    id: 'fin2',
    memberId: 'm2',
    cooperativeId: 'coop1',
    shares: 15,
    totalContributions: 750000,
    savings: 380000,
    dividends: 105000,
    loans: 0,
    lastUpdated: '2025-10-01',
  },
  {
    id: 'fin3',
    memberId: 'm3',
    cooperativeId: 'coop1',
    shares: 12,
    totalContributions: 600000,
    savings: 300000,
    dividends: 84000,
    loans: 0,
    lastUpdated: '2025-10-01',
  },
  {
    id: 'fin4',
    memberId: 'm4',
    cooperativeId: 'coop1',
    shares: 10,
    totalContributions: 500000,
    savings: 250000,
    dividends: 70000,
    loans: 0,
    lastUpdated: '2025-10-01',
  },
  {
    id: 'fin5',
    memberId: 'm5',
    cooperativeId: 'coop1',
    shares: 9,
    totalContributions: 450000,
    savings: 225000,
    dividends: 63000,
    loans: 0,
    lastUpdated: '2025-10-01',
  },
];
